### ISSUE TITLE
Hi there!

### ISSUE THREAD

**Issue by xiaoyu2006** [whywhatsmg/whywhatsmg#1]
Please comfirm:
 - ME: Yi Cao
 - YOU: Yang Sheng

**Comment by xiaoyu2006** [comment]
OK, `Yang shen` right?

**Comment by whywhatsmg** [comment]
Ah!

**Comment by whywhatsmg** [comment]
How can I send my issue to you?

**Comment by xiaoyu2006** [comment]
> How can I send my issue to you?

What does `send my issue to you` mean?

**Comment by whywhatsmg** [comment]
It just means how can I send it to your email

**Comment by whywhatsmg** [comment]
![批注 2020-04-23 100156](https://user-images.githubusercontent.com/62283914/80050934-81805700-8549-11ea-91c2-d077b5f056d3.png)
Because I also found it here.

**Comment by whywhatsmg** [comment]
Where are you now?

**Comment by xiaoyu2006** [comment]
Yes?

**Comment by xiaoyu2006** [comment]
> It just means how can I send it to your email

Any comments or changes will automatically be sent to your email.

**Comment by whywhatsmg** [comment]
All right.

**Comment by whywhatsmg** [comment]
> > It just means how can I send it to your email
> 
> Any comments or changes will automatically be sent to your email.

All right.
